### ISSUE TITLE
Change NvimTree background

### ISSUE THREAD

**Issue by majjejjam** [Mofiqul/adwaita.nvim#10]
In Builder the background of the file tree is slightly different compared to that of the source editor:

![Skärmbild från 2022-05-07 08-53-59](https://user-images.githubusercontent.com/58899295/167244644-4ad47d2b-4677-45a6-a9d7-3db36af45ca6.png)
![Skärmbild från 2022-05-07 09-40-39](https://user-images.githubusercontent.com/58899295/167244646-af59106b-88fa-49d0-a503-6ba490ca2446.png)

(Screenshots from the GTK4 port.)

I think changing the NvimTree highlighting to match this would look better and be more accurate! I started doing this myself but realized the dark file tree highlighting (`#1e1e1e`) is “bound” to the `adwaita_darker` option, so I wasn’t sure how it should be restructured. Also, I didn’t manage to make the cursorline highlight the part to the left of the icons.

**Comment by Mofiqul** [comment]
For `adwaita_darker` version `nvim-tree` can use something darker like `#101010`

**Comment by majjejjam** [comment]
I”ve created a pull request now, feel free to review it!
