### ISSUE TITLE
`CmpItemKind` `highlight` has background

### ISSUE THREAD

**Issue by majjejjam** [Mofiqul/adwaita.nvim#14]
`CmpItemKind` links to `Pmenu`, which has a background, so the line highlighting looks weird. I don't know if it's best to remove the background from `Pmenu`, or link `CmpItemKind` to something else.

The snippet at the top doesn't have the same issue – I don't really know why.

![bild](https://user-images.githubusercontent.com/58899295/171879466-cd2f6c42-7eee-4c53-a08e-48b562c3602f.png)

**Comment by Mofiqul** [comment]
I think something is wrong with your conf. It supposed to look like this

![Screenshot from 2022-06-04 09-11-19](https://user-images.githubusercontent.com/23612580/171980608-21c4bbe8-2606-4332-b5f6-5e91952f40bf.png)

**Comment by majjejjam** [comment]
It seems to have to do with `nvim-cmp` `window` settings. Leaving them default, I get the same as you:

![Skärmbild från 2022-06-04 19-21-33](https://user-images.githubusercontent.com/58899295/172018459-40cba890-e3d1-4de1-89c9-6882fb12448a.png)

But changing them to
```lua
window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
},
```
I get

![Skärmbild från 2022-06-04 19-20-59](https://user-images.githubusercontent.com/58899295/172018461-a8ccffbc-64fb-4b08-abe4-bdf28ee5dcdd.png)

**Comment by Mofiqul** [comment]
It has been fixed now

**Comment by majjejjam** [comment]
Awesome, thanks!
