### ISSUE TITLE
Reference/source for the colors been used

### ISSUE THREAD

**Issue by saccarosium** [Mofiqul/adwaita.nvim#21]
Hi,
Would be nice having the source you've used for this colorscheme in something like `CONTRIBUTE.md` or in the `README.md`. This would make it significantly more easy do modification and PRs based on the same reference.

By searching around I found [this](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html#palette-colors).

**Comment by Mofiqul** [comment]
The colors are taken from gtksourceview5 color schemes. Please see https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes. I will add it to README as well
