### ISSUE TITLE
Improve comments contrast

### ISSUE THREAD

**Issue by malobre** [Mofiqul/adwaita.nvim#23]
Comments are quite hard to read with current settings (i.e: https://contrast-ratio.com/#%2377767B-on-%231D1D1D),
could you consider changing there colors to `light_6` (i.e: https://contrast-ratio.com/#%23B0AFAC-on-%231D1D1D) ?

**Comment by Mofiqul** [comment]
@malobre - yah i will fix that. thanks for report

**Comment by malobre** [comment]
If you are interested in accessibility you might want to check out APCA, it is a new and improved contrast method (see "[Why APCA?](https://github.com/Myndex/SAPC-APCA/blob/747f2c3daecdbd6f54587bf1224607f382659b36/documentation/WhyAPCA.md)").

Also check out this [APCA Contrast Calculator](https://www.myndex.com/APCA/).

If you are busy I could take a look and submit a PR.

**Comment by Mofiqul** [comment]
@malobre - If you can, please make a PR. I am a bit busy these days, but I will check the PR.
