### ISSUE TITLE
Recent commit broke the colorsceme

### ISSUE THREAD

**Issue by REmerald** [Mofiqul/adwaita.nvim#25]
Basically, see the screenshot
![image](https://user-images.githubusercontent.com/55359236/228228183-f27da199-dd72-41b4-af49-058007775bb0.png)

VS the screenshot when I rolled back to the older commit
![image](https://user-images.githubusercontent.com/55359236/228229215-5e695c6d-f217-44ac-a068-313dcae9248e.png)

Idk, if this was intended or not, but it certainly messed up listchars and non-bold yellow, making it almost unusable.

Also, about the seemingly more intended changes, I think most of them are good (e.g. blue `\n`, green number literals, etc.), while some of them are not: I think whitish comments and pink `break` statements are more readable.

**Comment by REmerald** [comment]
Hmm, that's definitely better now:
![image](https://user-images.githubusercontent.com/55359236/228550294-c04e6a99-1ecb-40cf-b5ca-3e5032b774ed.png)

Except one thing, macros (e.g. `EXIT_FAILURE` and `EOF`) should be colored the same way as variables: non-bold unless they're marked "special" by treesitter (look at the `stdin`, `stderr` vars); take a look at the old commit version (see how `NULL` is bold here?):
![image](https://user-images.githubusercontent.com/55359236/228543316-adfacb55-827b-4617-91b0-5a9795cd4599.png)
This makes statements with macros way more readable (or more pleasing to read, at least). So, please make it this way.

Btw, are underlined `'listchars'` intended feature? If yes, how can I disable it?

About everything else I think it's good (I changed my mind about `break`, I like them bold-yellow now), but I miss whitish comments though...  
But that's up to you and not a problem for me, I can easily override it.  
Just, please fix the macros...

**Comment by Mofiqul** [comment]
@REmerald - Listchars underlined is not intended. Can you share your listchars so that i can replicate them. and about the macro i will fix.

**Comment by REmerald** [comment]
@Mofiqul , here:
```
	list         = true,  -- mark different blank chars
	listchars    = "tab:→·,trail:¤,multispace: »,nbsp:░,extends:►,precedes:◄",

```
In other colorschemes they are not underlined.

Btw, vscode.nvim and dracula.nvim have the same problem with macros:
![image](https://user-images.githubusercontent.com/55359236/228820848-e5f54d59-b89b-4e0d-9620-9d2351f40130.png)

**Comment by Mofiqul** [comment]
@REmerald - update the theme. I added the fixes

**Comment by REmerald** [comment]
@Mofiqul thanks for the listchars fix.

Though there's now the problem that neither vars nor macros that are "special" are marked bold now:
![image](https://user-images.githubusercontent.com/55359236/229102664-69b44e83-6ef3-455c-8297-c7190c741e64.png)

But I know how to fix it:
```
    hl('@constant.builtin', { fg = colors.violet_2, bold = true })
    hl('@constant.macro', { fg = colors.orange_2, bold = true })
```
This brings back the boldness of the `NULL` macro and special variables (`stdin`, `stderr`, etc.) as well:
![image](https://user-images.githubusercontent.com/55359236/229102541-a54b3c5f-9651-43a6-ab7c-fa455aecf2a2.png)

**Comment by REmerald** [comment]
@Mofiqul - commit `dc92272` fixed it, but the next one (`8358d04`) broke it again.

Commit `dc92272`:
![image](https://user-images.githubusercontent.com/55359236/229348250-6fbacec8-51ea-4690-98c7-bda45dc777db.png)

VS upstream:
![image](https://user-images.githubusercontent.com/55359236/229348296-b690f461-b858-414f-b41a-2f5d44658cd2.png)
It made all macros bold again, and, also, normal variables became white (or no-color?).

**Comment by Mofiqul** [comment]
Are you using clangd? I think lsp symantic token are affecting. Can you `: Inspect`

**Comment by REmerald** [comment]
@Mofiqul I do, and I just noticed, if I do `:LspStop` (currently testing on the old commit `dc92272`), normal variables turn from yellow to white and special vars/macros turn to purple. If I `:LspStart` the indentifiers turn to yellow again.

UPD: So, I just updated to the latest commit and did `:LspStop`, and it worked:
![image](https://user-images.githubusercontent.com/55359236/229374071-621643db-9696-44f5-9336-2c5b5caca211.png)

Here are the tokens:

1.  variable `lbuf`, unchanged by the lsp:
```
  - @variable.c links to @variable c
  - @lsp.type.variable.c links to @variable priority: 125
  - @lsp.mod.functionScope.c links to @lsp priority: 126
  - @lsp.typemod.variable.functionScope.c links to @lsp priority: 127
```
2. special variables `stdin`, `stdout`, etc., changed to bold yellow by the lsp:
```
  - @variable.c links to @variable c
  - @constant.builtin.c links to @constant.builtin c
  - @lsp.type.macro.c links to @macro priority: 125
  - @lsp.mod.globalScope.c links to @lsp priority: 126
  - @lsp.typemod.macro.globalScope.c links to @lsp priority: 127
```
3. macros `EOF`, `EXIT_FAILURE`, etc., changed to bold yellow:
```
  - @variable.c links to @variable c
  - @constant.c links to @constant c
  - @lsp.type.macro.c links to @macro priority: 125
  - @lsp.mod.globalScope.c links to @lsp priority: 126
  - @lsp.typemod.macro.globalScope.c links to @lsp priority: 127
```
4. special macro `NULL`, changed by lsp;
```
  - @constant.builtin.c links to @constant.builtin c
  - @lsp.type.macro.c links to @macro priority: 125
  - @lsp.mod.globalScope.c links to @lsp priority: 126
  - @lsp.typemod.macro.globalScope.c links to @lsp priority: 127
```

PS: Hmm, so maybe the solution (for now) would be to make `@macro` non-bold:
```
hl('@macro', { fg = colors.orange_2 })
```
But it would be hard to make special macros, like `NULL` bold though...

**Comment by REmerald** [comment]
@Mofiqul - just figured out that it's a global issue: the lsp changes the color in other colorschemes as well...

But now idk whose fault it is...  clangd, treesitter or lspconfig?
So, can you give me an advice, where I should open an issue about it?

**Comment by REmerald** [comment]
Seems like it's "treesitter vs clangd" issue, because treesitter treats macros as `@variable` (sometimes `@constant.builtin`), but clangd - as `@macro`.

So, for now, the only proper way to fix it is to put this in the `on_attach`:
```
if client.name == "clangd" then
	-- Disable the conflicting (with treesitter) group
	vim.api.nvim_set_hl(0, "@lsp.type.macro", {})
	-- OR
	-- Completely disable semantic highlighting
	-- client.server_capabilities.semanticTokensProvider = nil
end
```
