### ISSUE TITLE
highlight group is `FoldedColumn` instead of `FoldColumn`

### ISSUE THREAD

**Issue by p00f** [Mofiqul/adwaita.nvim#27]
https://github.com/Mofiqul/adwaita.nvim/blob/7b27d8f2e9cf4092e6752e67991c1b64f60a020c/lua/adwaita/dark.lua#L54

This should be `FoldColumn`: https://neovim.io/doc/user/syntax.html#hl-FoldColumn

**Comment by Mofiqul** [comment]
@p00f - Nice catch. I will fix it soon

**Comment by p00f** [comment]
@Mofiqul you changed it to `FoldeColumn`, it's `FoldColumn`

**Comment by Mofiqul** [comment]
> @Mofiqul you changed it to `FoldeColumn`, it's `FoldColumn`

I am a moron. I will fix it asap
