### ISSUE TITLE
Colorcolumn too dark on Adwaita light?

### ISSUE THREAD

**Issue by iGormilhit** [Mofiqul/adwaita.nvim#35]
On the Adwaita light theme, I think (or find), that the `colorcolumn` is too dark. The user attention is way too much attracted to it and it makes the characters under it hard to read.

So I think that in the following line, `dark_1` should be changed to `light_3`.

https://github.com/Mofiqul/adwaita.nvim/blob/981bce791959d79cd1316e59e23906e3c05efb44/lua/adwaita/light.lua#L34

By the way, I also think that the Adwaita background is white, so `light_1` instead of `light_2`. At least it would be consistent with the gnome-terminal background.

https://github.com/Mofiqul/adwaita.nvim/blob/981bce791959d79cd1316e59e23906e3c05efb44/lua/adwaita/light.lua#L26

I can propose a PR if needed. But first, I would like to know other opinions on this.

**Comment by Mofiqul** [comment]
Please do a PR with changes. Please attach the screen shot of before and after
