### ISSUE TITLE
Cursor is invisible in spaces

### ISSUE THREAD

**Issue by CleoMenezesJr** [Mofiqul/adwaita.nvim#9]
https://user-images.githubusercontent.com/54215258/163820007-2d3eb84a-6377-4c46-b7ea-d9db8d50de57.mp4

**Comment by Mofiqul** [comment]
I can not reproduce it. Did you somewhere override the `Cursor` highlight somewhere in your config?

**Comment by majjejjam** [comment]
I have the same issue and can’t find anywhere in my config overriding the `Cursor` highlight. When disabling `cursorline`, the cursor becomes visible, so it seems to have the same highlight as `cursorline` in spaces.

**Comment by majjejjam** [comment]
I’m not sure it’s related, but adding an option to disable `cursorline` highlighting does not solve the issue. I also think it’s better not to have such an option, as it is already built into vim (`set nocul`).

Also, even without `cul`, the contrast between the `Cursor` highlight and background isn’t that strong. I realized the highlight of the `Cursor` differs from being on a blank line and being in space or tabs. Maybe they should be the same?

**Comment by Mofiqul** [comment]
Disable cursor line I added because even there is no cursorline I wanted to highlight `CurosrLineNr`. The problem is the cursor picking up the background from text under it. Doing `:hi! Cursor ...` does not do anything. Right now I can't figure out what's happening, but I found this https://github.com/neovim/neovim/issues/6591

**Comment by majjejjam** [comment]
Oh, okay.

It seems like a more complicated issue than I first though. It’s weird how it only affects some spaces/tabs, the ones in source code files. If you open up a regular text file and put some spaces there, the highlighting is correct.

**Comment by Mofiqul** [comment]
I also noticed that setting `vim.opt.list = false` makes somewhat better.
